#bin/bash
#PBS -N simulation_2_uni
#PBS be
#PBS -o ${HOME}/sandia/sandia_code/simulations/simulation_2/output_uni/o_files/output.log
#PBS -e ${HOME}/sandia/sandia_code/simulations/simulation_2/output_uni/e_files/error.log
#PBS -q parallel8
#PBS -t 0-299

echo "PBS_ARRAYID is set to: ${PBS_ARRAYID}"

cd ${HOME}/sandia/sandia_code/simulations/simulation_2
export PYTHONPATH=${HOME}/sandia/sandia_code

source ${HOME}/sandia/sandia_venv/bin/activate
which python3

python3 -u simulation_2_uni.py > "output_uni/progress_output/simulation_2_uni_output_$PBS_ARRAYID.out"
